using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DataIntegrationService.Helpers
{
    public class GlobalConstants
    {
        public const string KEmployeeBasicDetails = "BTEmployeeBasicDetails";
        public const string KEmployeeNumber = "EmployeeNumber";
        public const string KAadharAddress = "AadharAddress";
        public const string KAadharNo = "AadharNo";
        public const string KAadharVerified = "AadharVerified";
        public const string KActive = "Active";
        public const string KBloodGroup = "BloodGroup";
        public const string KColorCode = "ColorCode";
        public const string KCustomer = "Customer";
        public const string KCustomerLocation= "CustomerLocation";
        public const string KDateofBirth = "DateofBirth";
        public const string KDateofVerification = "DateofVerification";
        public const string KEmail = "Email";
        public const string KEsiNo = "EsiNo";
        public const string KFatherName = "FatherName";
        public const string KGender = "Gender";
        public const string KHomePhone = "HomePhone";
        public const string KJobRoleName = "JobRoleName";
        public const string KLastName = "LastName";
        public const string KLocationName = "LocationName";
        public const string KMaritalStatus = "MaritalStatus";
        public const string KMiddleName = "MiddleName";
        public const string KMobileNo = "MobileNo";
        public const string KMotherName = "MotherName";
        public const string KName = "Name";
        public const string KOrganizationName = "OrganizationName";
        public const string KOtherName = "OtherName";
        public const string KRegion = "Region";
        public const string KSpouseName = "SpouseName";
        public const string KStatus = "Status";
        public const string KVerifier = "Verifier";
        public const string KWorkLocation = "WorkLocation";
        public const string KWorkLocationName = "WorkLocationName";
        public const string KBTEmployeeBasicDetailsAddress = "BTEmployeeBasicDetailsAddress";
        public const string KEmployeeNo = "EmployeeNo";
        public const string KAddress1 = "Address1";
        public const string KAddress2 = "Address2";
        public const string KAddress3 = "Address3";
        public const string KCity = "City";
        public const string KState = "State";
        public const string KCountry = "Country";
        public const string KZipCode = "ZipCode";
        public const string KBTAdditionalDetails = "BTAdditionalDetails";
        public const string KPosition = "Position";
        public const string KEmployeeType = "EmployeeType";
        public const string KDepartment = "Department";
        public const string KDesignation = "Designation";
        public const string KJoiningDate = "JoiningDate";
        public const string KHQualification = "HQualification";
        public const string KPresAddress = "PresAddress";
        public const string KPremAddress = "PremAddress";
        public const string KBTAadharDetails = "BTAadharDetails";
        public const string KCo = "Co";
        public const string KDistrict = "District";
        public const string KFailureReason = "FailureReason";
        public const string KHouse = "House";
        public const string KId = "Id";
        public const string KLandmark = "Landmark";
        public const string KLc = "Lc";
        public const string KNew = "New";
        public const string KPhoneNumber = "PhoneNumber";
        public const string KPincode = "Pincode";
        public const string KPostOffice = "PostOffice";
        public const string KSaveResponse = "SaveResponse";
        public const string KStreet = "Street";
        public const string KSubdistrict = "Subdistrict";
        public const string KUIDTag = "UIDTag";
        public const string KUuId = "UuId";
        public const string KVtc = "Vtc";
        public const string KBTCurrentAddress = "BTCurrentAddress";
        public const string KPostalCode = "PostalCode";
        public const string KBTBankDetails = "BTBankDetails";
        public const string KPANNumber = "PANNumber";
        public const string KBankAccountNumber = "BankAccountNumber";
        public const string KIFSCCode = "IFSCCode";
        public const string KBankName = "BankName";
        public const string KBankBranch = "BankBranch";
        public const string KAddress = "Address";
        public const string KFileUpload = "FileUpload";
        public const string KBTPFDetails = "BTPFDetails";
        public const string KNoPFAccount = "NoPFAccount";
        public const string KBTFamilyDetails = "BTFamilyDetails";
        public const string KPreviousPFAccountNumber = "PreviousPFAccountNumber";
        public const string KdateOfExitFromPreviousEmployment = "dateOfExitFromPreviousEmployment";
        public const string KschemeCertificateNoIfIssued = "schemeCertificateNoIfIssued";
        public const string KppoNumberIfIssued = "ppoNumberIfIssued";
        public const string KinternationalWorkerYesno = "internationalWorkerYesno";
        public const string KifYesNameOfTheCountry= "ifYesNameOfTheCountry";
        public const string KpfNumber = "pfNumber";
        public const string KplaceOfIssue = "placeOfIssue";
        public const string KdateOfIssue = "dateOfIssue";
        public const string KIssuingAuthority = "IssuingAuthority";
        public const string KValidFrom = "ValidFrom";
        public const string KPreviousEmploymentUAN = "PreviousEmploymentUAN";
        public const string KisFromNortheastnepalbhutan = "isFromNortheastnepalbhutan";
        public const string KuanNumber = "uanNumber";
        public const string KPFDocUpload = "PFDocUpload";
        public const string KBTPermanentAddress = "BTPermanentAddress";
        public const string KAddressAsPerAadhar = "AddressAsPerAadhar";
        public const string KAddressAsPerCurrentAddress = "AddressAsPerCurrentAddress";
        public const string KNameasPerAadhar = "NameasPerAadhar";
        public const string KRelationshipWithEmployee = "RelationshipWithEmployee";
        public const string KDOB = "DOB";
        public const string KDependentYN = "DependentYN";
        public const string KResidingWithEmployee = "ResidingWithEmployee";
        public const string KFamilyDetailsDocument = "FamilyDetailsDocument";
        public const string KBTNomineeDetails = "BTNomineeDetails";
        public const string KSupportingDoc1Upload = "SupportingDoc1Upload";
        public const string StartTimeformat = "yyyy-MM-dd 00:00:00";
        public const string EndTimeformat = "yyyy-MM-dd HH:mm:ss";

    }
}